@startuml  
actor Клиент as Клиент  
actor Сервер as Сервер  
  
Client -> Сервер : Открытие сайта  
activate Сервер  
  
Сервер --> Клиент : Ответ сервера (HTML)  
deactivate Сервер  
  
Клиент --> Сервер : Запрос товара  
activate Сервер  
  
Сервер --> Клиент : Ответ с товаром  
deactivate Сервер  
  
Клиент --> Сервер : Запрос на оплату  
activate Сервер  
  
Сервер --> Клиент : Подтверждение оплаты  
deactivate Сервер  
  
Клиент --> Сервер : Запрос на доставку  
activate Сервер  
  
Сервер --> Клиент : Подтверждение доставки  
deactivate Сервер  
@enduml 
